### ISSUE TITLE
zip_file module status?

### ISSUE THREAD

**Issue by rmtheis** [bolein/better-apk-expansion#5]
I noticed that the `zip_file` module classes aren't available to users of this library. Is this intended? It would be helpful to users, myself included, to be able to use those classes when using the library.

In any case, I would volunteer to do a small update to the readme to clarify.

**Comment by bolein** [comment]
@rmtheis I just didn't get my hands on it yet. 'zip_file' module has to be reorganized to be compiled with Gradle.

**Comment by bolein** [comment]
@rmtheis you may now include `zip_file` classes using the following dependency:
```
compile 'com.github.bolein.better-apk-expansion:zip_file:5.0.2'
```

Please note that the dependency for the downloader library has also been changed:
```
compile 'com.github.bolein.better-apk-expansion:downloader_library:5.0.2'
```

**Comment by rmtheis** [comment]
Nice! Thank you!
