### ISSUE TITLE
Couple of issues 

### ISSUE THREAD

**Issue by mhemdan** [bolein/better-apk-expansion#9]
First of thanks for this library but there are no full Sample for how to use it actually it will be really helpful as from the readme there are some missing things I can't implement the flow from it.

**Comment by bolein** [comment]
Thanks for the feedback. I hope to find some time to create a sample app. But I think that the use is pretty easy. All you have to do is just start the download by calling 
```JAVA
int startResult = DownloaderService.startDownloadServiceIfRequired(this,
                        "downloader-channel",
                        pendingIntent, SALT, BASE64_PUBLIC_KEY);
```
And then just listen to the download progress with `DownloaderClient` which has a very simple API (see the readme).

Do you have any specific problem I can help you with?

**Comment by mhemdan** [comment]
Thanks for your prompt reply
Steps are. : 
1- checking if for " expansionFilesDelivered() "
2- start download with 
`int startResult = DownloaderService.startDownloadServiceIfRequired(this,
                        "downloader-channel",
                        pendingIntent, SALT, BASE64_PUBLIC_KEY);`
3- and for listening to downloader client using this 
`   class DownloaderClient extends BroadcastDownloaderClient {
    
        @Override 
        public void onDownloadStateChanged(int newState) {
            if (newState == STATE_COMPLETED) {
                // downloaded successfully...
            } else if (newState >= 15) {
                // failed
                int message = Helpers.getDownloaderStringResourceIDFromState(newState);
                Toast.makeText(SampleDownloaderActivity.this, message, Toast.LENGTH_SHORT).show();
            } 
        }
        
        @Override 
        public void onDownloadProgress(DownloadProgressInfo progressInfo) {
            if (progressInfo.mOverallTotal > 0) {
                // receive the download progress
                // you can then display the progress in your activity
                String progress = Helpers.getDownloadProgressPercent(progressInfo.mOverallProgress,
                    progressInfo.mOverallTotal);
                Log.i("SampleDownloaderActivity", "downloading progress: " + progress);
            }
        }
    }`
4- you didn't mention how to access this downloaded files or is the normal way as in android guide.

**Comment by bolein** [comment]
@mhemdan yes, you should access the downloaded files the same way you do it with the official guide. See the [getObbDir](https://developer.android.com/reference/android/content/Context.html#getObbDir()) reference.
